// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/planet.proto

package com.fr.planet;

public final class PlanetsTraining {
  private PlanetsTraining() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlanetsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:planets.Planets)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    java.util.List<com.fr.planet.PlanetsTraining.Planet> 
        getPlanetList();
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    com.fr.planet.PlanetsTraining.Planet getPlanet(int index);
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    int getPlanetCount();
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    java.util.List<? extends com.fr.planet.PlanetsTraining.PlanetOrBuilder> 
        getPlanetOrBuilderList();
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    com.fr.planet.PlanetsTraining.PlanetOrBuilder getPlanetOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code planets.Planets}
   */
  public  static final class Planets extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:planets.Planets)
      PlanetsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Planets.newBuilder() to construct.
    private Planets(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Planets() {
      planet_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Planets(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                planet_ = new java.util.ArrayList<com.fr.planet.PlanetsTraining.Planet>();
                mutable_bitField0_ |= 0x00000001;
              }
              planet_.add(
                  input.readMessage(com.fr.planet.PlanetsTraining.Planet.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          planet_ = java.util.Collections.unmodifiableList(planet_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fr.planet.PlanetsTraining.internal_static_planets_Planets_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fr.planet.PlanetsTraining.internal_static_planets_Planets_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fr.planet.PlanetsTraining.Planets.class, com.fr.planet.PlanetsTraining.Planets.Builder.class);
    }

    public static final int PLANET_FIELD_NUMBER = 1;
    private java.util.List<com.fr.planet.PlanetsTraining.Planet> planet_;
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    public java.util.List<com.fr.planet.PlanetsTraining.Planet> getPlanetList() {
      return planet_;
    }
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    public java.util.List<? extends com.fr.planet.PlanetsTraining.PlanetOrBuilder> 
        getPlanetOrBuilderList() {
      return planet_;
    }
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    public int getPlanetCount() {
      return planet_.size();
    }
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    public com.fr.planet.PlanetsTraining.Planet getPlanet(int index) {
      return planet_.get(index);
    }
    /**
     * <code>repeated .planets.Planet Planet = 1;</code>
     */
    public com.fr.planet.PlanetsTraining.PlanetOrBuilder getPlanetOrBuilder(
        int index) {
      return planet_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < planet_.size(); i++) {
        output.writeMessage(1, planet_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < planet_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, planet_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fr.planet.PlanetsTraining.Planets)) {
        return super.equals(obj);
      }
      com.fr.planet.PlanetsTraining.Planets other = (com.fr.planet.PlanetsTraining.Planets) obj;

      boolean result = true;
      result = result && getPlanetList()
          .equals(other.getPlanetList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPlanetCount() > 0) {
        hash = (37 * hash) + PLANET_FIELD_NUMBER;
        hash = (53 * hash) + getPlanetList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fr.planet.PlanetsTraining.Planets parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Planets parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fr.planet.PlanetsTraining.Planets prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code planets.Planets}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:planets.Planets)
        com.fr.planet.PlanetsTraining.PlanetsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Planets_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Planets_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fr.planet.PlanetsTraining.Planets.class, com.fr.planet.PlanetsTraining.Planets.Builder.class);
      }

      // Construct using com.fr.planet.PlanetsTraining.Planets.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlanetFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (planetBuilder_ == null) {
          planet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          planetBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Planets_descriptor;
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Planets getDefaultInstanceForType() {
        return com.fr.planet.PlanetsTraining.Planets.getDefaultInstance();
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Planets build() {
        com.fr.planet.PlanetsTraining.Planets result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Planets buildPartial() {
        com.fr.planet.PlanetsTraining.Planets result = new com.fr.planet.PlanetsTraining.Planets(this);
        int from_bitField0_ = bitField0_;
        if (planetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            planet_ = java.util.Collections.unmodifiableList(planet_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.planet_ = planet_;
        } else {
          result.planet_ = planetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fr.planet.PlanetsTraining.Planets) {
          return mergeFrom((com.fr.planet.PlanetsTraining.Planets)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fr.planet.PlanetsTraining.Planets other) {
        if (other == com.fr.planet.PlanetsTraining.Planets.getDefaultInstance()) return this;
        if (planetBuilder_ == null) {
          if (!other.planet_.isEmpty()) {
            if (planet_.isEmpty()) {
              planet_ = other.planet_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlanetIsMutable();
              planet_.addAll(other.planet_);
            }
            onChanged();
          }
        } else {
          if (!other.planet_.isEmpty()) {
            if (planetBuilder_.isEmpty()) {
              planetBuilder_.dispose();
              planetBuilder_ = null;
              planet_ = other.planet_;
              bitField0_ = (bitField0_ & ~0x00000001);
              planetBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlanetFieldBuilder() : null;
            } else {
              planetBuilder_.addAllMessages(other.planet_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fr.planet.PlanetsTraining.Planets parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fr.planet.PlanetsTraining.Planets) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.fr.planet.PlanetsTraining.Planet> planet_ =
        java.util.Collections.emptyList();
      private void ensurePlanetIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          planet_ = new java.util.ArrayList<com.fr.planet.PlanetsTraining.Planet>(planet_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fr.planet.PlanetsTraining.Planet, com.fr.planet.PlanetsTraining.Planet.Builder, com.fr.planet.PlanetsTraining.PlanetOrBuilder> planetBuilder_;

      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public java.util.List<com.fr.planet.PlanetsTraining.Planet> getPlanetList() {
        if (planetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(planet_);
        } else {
          return planetBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public int getPlanetCount() {
        if (planetBuilder_ == null) {
          return planet_.size();
        } else {
          return planetBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public com.fr.planet.PlanetsTraining.Planet getPlanet(int index) {
        if (planetBuilder_ == null) {
          return planet_.get(index);
        } else {
          return planetBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder setPlanet(
          int index, com.fr.planet.PlanetsTraining.Planet value) {
        if (planetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlanetIsMutable();
          planet_.set(index, value);
          onChanged();
        } else {
          planetBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder setPlanet(
          int index, com.fr.planet.PlanetsTraining.Planet.Builder builderForValue) {
        if (planetBuilder_ == null) {
          ensurePlanetIsMutable();
          planet_.set(index, builderForValue.build());
          onChanged();
        } else {
          planetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder addPlanet(com.fr.planet.PlanetsTraining.Planet value) {
        if (planetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlanetIsMutable();
          planet_.add(value);
          onChanged();
        } else {
          planetBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder addPlanet(
          int index, com.fr.planet.PlanetsTraining.Planet value) {
        if (planetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlanetIsMutable();
          planet_.add(index, value);
          onChanged();
        } else {
          planetBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder addPlanet(
          com.fr.planet.PlanetsTraining.Planet.Builder builderForValue) {
        if (planetBuilder_ == null) {
          ensurePlanetIsMutable();
          planet_.add(builderForValue.build());
          onChanged();
        } else {
          planetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder addPlanet(
          int index, com.fr.planet.PlanetsTraining.Planet.Builder builderForValue) {
        if (planetBuilder_ == null) {
          ensurePlanetIsMutable();
          planet_.add(index, builderForValue.build());
          onChanged();
        } else {
          planetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder addAllPlanet(
          java.lang.Iterable<? extends com.fr.planet.PlanetsTraining.Planet> values) {
        if (planetBuilder_ == null) {
          ensurePlanetIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, planet_);
          onChanged();
        } else {
          planetBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder clearPlanet() {
        if (planetBuilder_ == null) {
          planet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          planetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public Builder removePlanet(int index) {
        if (planetBuilder_ == null) {
          ensurePlanetIsMutable();
          planet_.remove(index);
          onChanged();
        } else {
          planetBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public com.fr.planet.PlanetsTraining.Planet.Builder getPlanetBuilder(
          int index) {
        return getPlanetFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public com.fr.planet.PlanetsTraining.PlanetOrBuilder getPlanetOrBuilder(
          int index) {
        if (planetBuilder_ == null) {
          return planet_.get(index);  } else {
          return planetBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public java.util.List<? extends com.fr.planet.PlanetsTraining.PlanetOrBuilder> 
           getPlanetOrBuilderList() {
        if (planetBuilder_ != null) {
          return planetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(planet_);
        }
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public com.fr.planet.PlanetsTraining.Planet.Builder addPlanetBuilder() {
        return getPlanetFieldBuilder().addBuilder(
            com.fr.planet.PlanetsTraining.Planet.getDefaultInstance());
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public com.fr.planet.PlanetsTraining.Planet.Builder addPlanetBuilder(
          int index) {
        return getPlanetFieldBuilder().addBuilder(
            index, com.fr.planet.PlanetsTraining.Planet.getDefaultInstance());
      }
      /**
       * <code>repeated .planets.Planet Planet = 1;</code>
       */
      public java.util.List<com.fr.planet.PlanetsTraining.Planet.Builder> 
           getPlanetBuilderList() {
        return getPlanetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fr.planet.PlanetsTraining.Planet, com.fr.planet.PlanetsTraining.Planet.Builder, com.fr.planet.PlanetsTraining.PlanetOrBuilder> 
          getPlanetFieldBuilder() {
        if (planetBuilder_ == null) {
          planetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fr.planet.PlanetsTraining.Planet, com.fr.planet.PlanetsTraining.Planet.Builder, com.fr.planet.PlanetsTraining.PlanetOrBuilder>(
                  planet_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          planet_ = null;
        }
        return planetBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:planets.Planets)
    }

    // @@protoc_insertion_point(class_scope:planets.Planets)
    private static final com.fr.planet.PlanetsTraining.Planets DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fr.planet.PlanetsTraining.Planets();
    }

    public static com.fr.planet.PlanetsTraining.Planets getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Planets>
        PARSER = new com.google.protobuf.AbstractParser<Planets>() {
      @java.lang.Override
      public Planets parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Planets(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Planets> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Planets> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fr.planet.PlanetsTraining.Planets getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlanetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:planets.Planet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    java.util.List<com.fr.planet.PlanetsTraining.Satellite> 
        getSatelliteList();
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    com.fr.planet.PlanetsTraining.Satellite getSatellite(int index);
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    int getSatelliteCount();
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    java.util.List<? extends com.fr.planet.PlanetsTraining.SatelliteOrBuilder> 
        getSatelliteOrBuilderList();
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    com.fr.planet.PlanetsTraining.SatelliteOrBuilder getSatelliteOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code planets.Planet}
   */
  public  static final class Planet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:planets.Planet)
      PlanetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Planet.newBuilder() to construct.
    private Planet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Planet() {
      id_ = 0;
      name_ = "";
      satellite_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Planet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                satellite_ = new java.util.ArrayList<com.fr.planet.PlanetsTraining.Satellite>();
                mutable_bitField0_ |= 0x00000004;
              }
              satellite_.add(
                  input.readMessage(com.fr.planet.PlanetsTraining.Satellite.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          satellite_ = java.util.Collections.unmodifiableList(satellite_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fr.planet.PlanetsTraining.internal_static_planets_Planet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fr.planet.PlanetsTraining.internal_static_planets_Planet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fr.planet.PlanetsTraining.Planet.class, com.fr.planet.PlanetsTraining.Planet.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SATELLITE_FIELD_NUMBER = 3;
    private java.util.List<com.fr.planet.PlanetsTraining.Satellite> satellite_;
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    public java.util.List<com.fr.planet.PlanetsTraining.Satellite> getSatelliteList() {
      return satellite_;
    }
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    public java.util.List<? extends com.fr.planet.PlanetsTraining.SatelliteOrBuilder> 
        getSatelliteOrBuilderList() {
      return satellite_;
    }
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    public int getSatelliteCount() {
      return satellite_.size();
    }
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    public com.fr.planet.PlanetsTraining.Satellite getSatellite(int index) {
      return satellite_.get(index);
    }
    /**
     * <code>repeated .planets.Satellite satellite = 3;</code>
     */
    public com.fr.planet.PlanetsTraining.SatelliteOrBuilder getSatelliteOrBuilder(
        int index) {
      return satellite_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < satellite_.size(); i++) {
        output.writeMessage(3, satellite_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < satellite_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, satellite_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fr.planet.PlanetsTraining.Planet)) {
        return super.equals(obj);
      }
      com.fr.planet.PlanetsTraining.Planet other = (com.fr.planet.PlanetsTraining.Planet) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getSatelliteList()
          .equals(other.getSatelliteList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getSatelliteCount() > 0) {
        hash = (37 * hash) + SATELLITE_FIELD_NUMBER;
        hash = (53 * hash) + getSatelliteList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fr.planet.PlanetsTraining.Planet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Planet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fr.planet.PlanetsTraining.Planet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code planets.Planet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:planets.Planet)
        com.fr.planet.PlanetsTraining.PlanetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Planet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Planet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fr.planet.PlanetsTraining.Planet.class, com.fr.planet.PlanetsTraining.Planet.Builder.class);
      }

      // Construct using com.fr.planet.PlanetsTraining.Planet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSatelliteFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (satelliteBuilder_ == null) {
          satellite_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          satelliteBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Planet_descriptor;
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Planet getDefaultInstanceForType() {
        return com.fr.planet.PlanetsTraining.Planet.getDefaultInstance();
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Planet build() {
        com.fr.planet.PlanetsTraining.Planet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Planet buildPartial() {
        com.fr.planet.PlanetsTraining.Planet result = new com.fr.planet.PlanetsTraining.Planet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (satelliteBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            satellite_ = java.util.Collections.unmodifiableList(satellite_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.satellite_ = satellite_;
        } else {
          result.satellite_ = satelliteBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fr.planet.PlanetsTraining.Planet) {
          return mergeFrom((com.fr.planet.PlanetsTraining.Planet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fr.planet.PlanetsTraining.Planet other) {
        if (other == com.fr.planet.PlanetsTraining.Planet.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (satelliteBuilder_ == null) {
          if (!other.satellite_.isEmpty()) {
            if (satellite_.isEmpty()) {
              satellite_ = other.satellite_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSatelliteIsMutable();
              satellite_.addAll(other.satellite_);
            }
            onChanged();
          }
        } else {
          if (!other.satellite_.isEmpty()) {
            if (satelliteBuilder_.isEmpty()) {
              satelliteBuilder_.dispose();
              satelliteBuilder_ = null;
              satellite_ = other.satellite_;
              bitField0_ = (bitField0_ & ~0x00000004);
              satelliteBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSatelliteFieldBuilder() : null;
            } else {
              satelliteBuilder_.addAllMessages(other.satellite_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fr.planet.PlanetsTraining.Planet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fr.planet.PlanetsTraining.Planet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.fr.planet.PlanetsTraining.Satellite> satellite_ =
        java.util.Collections.emptyList();
      private void ensureSatelliteIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          satellite_ = new java.util.ArrayList<com.fr.planet.PlanetsTraining.Satellite>(satellite_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fr.planet.PlanetsTraining.Satellite, com.fr.planet.PlanetsTraining.Satellite.Builder, com.fr.planet.PlanetsTraining.SatelliteOrBuilder> satelliteBuilder_;

      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public java.util.List<com.fr.planet.PlanetsTraining.Satellite> getSatelliteList() {
        if (satelliteBuilder_ == null) {
          return java.util.Collections.unmodifiableList(satellite_);
        } else {
          return satelliteBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public int getSatelliteCount() {
        if (satelliteBuilder_ == null) {
          return satellite_.size();
        } else {
          return satelliteBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public com.fr.planet.PlanetsTraining.Satellite getSatellite(int index) {
        if (satelliteBuilder_ == null) {
          return satellite_.get(index);
        } else {
          return satelliteBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder setSatellite(
          int index, com.fr.planet.PlanetsTraining.Satellite value) {
        if (satelliteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSatelliteIsMutable();
          satellite_.set(index, value);
          onChanged();
        } else {
          satelliteBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder setSatellite(
          int index, com.fr.planet.PlanetsTraining.Satellite.Builder builderForValue) {
        if (satelliteBuilder_ == null) {
          ensureSatelliteIsMutable();
          satellite_.set(index, builderForValue.build());
          onChanged();
        } else {
          satelliteBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder addSatellite(com.fr.planet.PlanetsTraining.Satellite value) {
        if (satelliteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSatelliteIsMutable();
          satellite_.add(value);
          onChanged();
        } else {
          satelliteBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder addSatellite(
          int index, com.fr.planet.PlanetsTraining.Satellite value) {
        if (satelliteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSatelliteIsMutable();
          satellite_.add(index, value);
          onChanged();
        } else {
          satelliteBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder addSatellite(
          com.fr.planet.PlanetsTraining.Satellite.Builder builderForValue) {
        if (satelliteBuilder_ == null) {
          ensureSatelliteIsMutable();
          satellite_.add(builderForValue.build());
          onChanged();
        } else {
          satelliteBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder addSatellite(
          int index, com.fr.planet.PlanetsTraining.Satellite.Builder builderForValue) {
        if (satelliteBuilder_ == null) {
          ensureSatelliteIsMutable();
          satellite_.add(index, builderForValue.build());
          onChanged();
        } else {
          satelliteBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder addAllSatellite(
          java.lang.Iterable<? extends com.fr.planet.PlanetsTraining.Satellite> values) {
        if (satelliteBuilder_ == null) {
          ensureSatelliteIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, satellite_);
          onChanged();
        } else {
          satelliteBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder clearSatellite() {
        if (satelliteBuilder_ == null) {
          satellite_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          satelliteBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public Builder removeSatellite(int index) {
        if (satelliteBuilder_ == null) {
          ensureSatelliteIsMutable();
          satellite_.remove(index);
          onChanged();
        } else {
          satelliteBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public com.fr.planet.PlanetsTraining.Satellite.Builder getSatelliteBuilder(
          int index) {
        return getSatelliteFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public com.fr.planet.PlanetsTraining.SatelliteOrBuilder getSatelliteOrBuilder(
          int index) {
        if (satelliteBuilder_ == null) {
          return satellite_.get(index);  } else {
          return satelliteBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public java.util.List<? extends com.fr.planet.PlanetsTraining.SatelliteOrBuilder> 
           getSatelliteOrBuilderList() {
        if (satelliteBuilder_ != null) {
          return satelliteBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(satellite_);
        }
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public com.fr.planet.PlanetsTraining.Satellite.Builder addSatelliteBuilder() {
        return getSatelliteFieldBuilder().addBuilder(
            com.fr.planet.PlanetsTraining.Satellite.getDefaultInstance());
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public com.fr.planet.PlanetsTraining.Satellite.Builder addSatelliteBuilder(
          int index) {
        return getSatelliteFieldBuilder().addBuilder(
            index, com.fr.planet.PlanetsTraining.Satellite.getDefaultInstance());
      }
      /**
       * <code>repeated .planets.Satellite satellite = 3;</code>
       */
      public java.util.List<com.fr.planet.PlanetsTraining.Satellite.Builder> 
           getSatelliteBuilderList() {
        return getSatelliteFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fr.planet.PlanetsTraining.Satellite, com.fr.planet.PlanetsTraining.Satellite.Builder, com.fr.planet.PlanetsTraining.SatelliteOrBuilder> 
          getSatelliteFieldBuilder() {
        if (satelliteBuilder_ == null) {
          satelliteBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fr.planet.PlanetsTraining.Satellite, com.fr.planet.PlanetsTraining.Satellite.Builder, com.fr.planet.PlanetsTraining.SatelliteOrBuilder>(
                  satellite_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          satellite_ = null;
        }
        return satelliteBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:planets.Planet)
    }

    // @@protoc_insertion_point(class_scope:planets.Planet)
    private static final com.fr.planet.PlanetsTraining.Planet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fr.planet.PlanetsTraining.Planet();
    }

    public static com.fr.planet.PlanetsTraining.Planet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Planet>
        PARSER = new com.google.protobuf.AbstractParser<Planet>() {
      @java.lang.Override
      public Planet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Planet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Planet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Planet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fr.planet.PlanetsTraining.Planet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SatelliteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:planets.Satellite)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code planets.Satellite}
   */
  public  static final class Satellite extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:planets.Satellite)
      SatelliteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Satellite.newBuilder() to construct.
    private Satellite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Satellite() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Satellite(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fr.planet.PlanetsTraining.internal_static_planets_Satellite_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fr.planet.PlanetsTraining.internal_static_planets_Satellite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fr.planet.PlanetsTraining.Satellite.class, com.fr.planet.PlanetsTraining.Satellite.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fr.planet.PlanetsTraining.Satellite)) {
        return super.equals(obj);
      }
      com.fr.planet.PlanetsTraining.Satellite other = (com.fr.planet.PlanetsTraining.Satellite) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fr.planet.PlanetsTraining.Satellite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fr.planet.PlanetsTraining.Satellite prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code planets.Satellite}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:planets.Satellite)
        com.fr.planet.PlanetsTraining.SatelliteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Satellite_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Satellite_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fr.planet.PlanetsTraining.Satellite.class, com.fr.planet.PlanetsTraining.Satellite.Builder.class);
      }

      // Construct using com.fr.planet.PlanetsTraining.Satellite.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fr.planet.PlanetsTraining.internal_static_planets_Satellite_descriptor;
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Satellite getDefaultInstanceForType() {
        return com.fr.planet.PlanetsTraining.Satellite.getDefaultInstance();
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Satellite build() {
        com.fr.planet.PlanetsTraining.Satellite result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fr.planet.PlanetsTraining.Satellite buildPartial() {
        com.fr.planet.PlanetsTraining.Satellite result = new com.fr.planet.PlanetsTraining.Satellite(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fr.planet.PlanetsTraining.Satellite) {
          return mergeFrom((com.fr.planet.PlanetsTraining.Satellite)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fr.planet.PlanetsTraining.Satellite other) {
        if (other == com.fr.planet.PlanetsTraining.Satellite.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fr.planet.PlanetsTraining.Satellite parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fr.planet.PlanetsTraining.Satellite) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:planets.Satellite)
    }

    // @@protoc_insertion_point(class_scope:planets.Satellite)
    private static final com.fr.planet.PlanetsTraining.Satellite DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fr.planet.PlanetsTraining.Satellite();
    }

    public static com.fr.planet.PlanetsTraining.Satellite getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Satellite>
        PARSER = new com.google.protobuf.AbstractParser<Satellite>() {
      @java.lang.Override
      public Satellite parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Satellite(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Satellite> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Satellite> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fr.planet.PlanetsTraining.Satellite getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_planets_Planets_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_planets_Planets_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_planets_Planet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_planets_Planet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_planets_Satellite_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_planets_Satellite_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026resources/planet.proto\022\007planets\"*\n\007Pla" +
      "nets\022\037\n\006Planet\030\001 \003(\0132\017.planets.Planet\"I\n" +
      "\006Planet\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022%\n\tsat" +
      "ellite\030\003 \003(\0132\022.planets.Satellite\"%\n\tSate" +
      "llite\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\tB \n\rcom.f" +
      "r.planetB\017PlanetsTrainingb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_planets_Planets_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_planets_Planets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_planets_Planets_descriptor,
        new java.lang.String[] { "Planet", });
    internal_static_planets_Planet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_planets_Planet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_planets_Planet_descriptor,
        new java.lang.String[] { "Id", "Name", "Satellite", });
    internal_static_planets_Satellite_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_planets_Satellite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_planets_Satellite_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
